name: deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Use Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install Serverless Framework
      run: |
        npm install -g serverless

    - name: Serverless Deploy
      run: |
        go mod download
        serverless deploy --stage prod
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
